### ISSUE TITLE
Should stop be stad

### ISSUE THREAD

**Issue by antoinog** [EoinDavey/Setanta#5]
Just discovered this today, very cool

**Comment by antoinog** [comment]
oh maybe both exist, my bad

**Comment by EoinDavey** [comment]
Hi,

Yes the stop vs stad issue did crop up, I went with stop because it's what I was taught, functions are first-order so you can always assign `stad := stop` if you'd prefer.

As you mentioned you discovered Setanta today, you might be interested in the new tutorials that are being developed at the moment. You can check them out at [dev.try-setanta.ie/tut/intro.html](https://dev.try-setanta.ie/tut/intro.html). (dev.try-setanta.ie is the non-production deployment of the site, the tutorials are only accessible there as they're still a WIP)
